packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - bcrypt
  - esbuild
  - '@nestjs/core'
  - '@parcel/watcher'
  - core-js
  - msgpackr-extract
